apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  labels:
    app: {{ .Release.Name }}-nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  rules:
  #- host: servers.kubernetes.course
   - http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-spring-app-service
            port:
              number: 8080

