apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-root-password
type: Opaque
stringData:
  password: root

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-username
type: Opaque
stringData:
  username: myuser

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-password
type: Opaque
stringData:
  password: mypassword