apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-spring-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-spring-app
    spec:
      containers:
          - name: {{ .Release.Name }}-spring-app-container
            image: {{ .Values.springApp.image.repository }}:{{ .Values.springApp.image.tag }}
            imagePullPolicy: {{ .Values.springApp.image.pullPolicy }}
            ports:
              - name: http
                containerPort: 8080
            env:
              - name: MYSQL_USER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-mysql-password
                    key: password
              - name: MYSQL_HOST
                value: {{ .Release.Name }}-mysql-service
              - name: MYSQL_DATABASE
                value: {{ .Values.mysql.databaseName }}
              - name: MYSQL_USER_NAME
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-mysql-username
                    key: username